# Programmeren 2.1

## Les 5.2 -- Verschillende soorten lijsten

6 Okt 2022

## Inhoud

- Lijsten herhaling
- *Nested* lijsten
- Ander soorten lijsten
  - **tuple**
  - **dict**
  - **set**
- Programmeerstijl

### Lijsten herhaling

Een lijst is een rij van waarden. Met lijsten kunnen we de volgende operaties uitvoeren:

| Code | Betekenis | Alternatief |
|:-----|:----------|:------------|
| **xs[i]** | $i^{de}$ waarde van de lijst ||
| **xs + ys** | Plak lijsten **xs** en **ys** achter elkaar ||
| **xs \* n** | Plak **n** kopien van **xs** achter elkaar ||
| **x in xs** | Zit **x** in de lijst **xs**? (True/False) ||
| **xs.append(x)** | Verleng **xs** met element **x** | **xs = xs + [x]** |
| **xs.extend(ys)** | Verleng **xs** met lijst **ys** | **xs = xs + ys** |
| **ys = xs** | **ys** verwijst naar dezelfde lijst als **xs** ||
| **ys = xs.copy()** | **ys** is een kopie van **xs** ||

Merk op: een string is een lijst van karakters, de **[i]**, **+** en **\*** operaties doen precies wat je zou verwachten.

- Indices van een lijst beginnen bij 0 en gaan tot (maar niet met) $n$, waar $n$ de lengte van de lijst is.
- Negatieve indices tellen van het eind van de lijst terug, dus -1 is het laatste element $(n-1)$, -2 is het één na laatste element $(n-2)$, etc...

In [1]:
xs = [2, 3, 5, 7, 11, 13, 17, 19]
print(xs[-1], xs[-2], xs[-3])

19 17 13


- Je kan deellijsten maken met '**[a:b]**', dit is een lijst met de element van index **a** tot (maar niet met) **b**.
- Als je **a** weglaat dan start je bij het begin van de lijst, als je **b** weglaat dan eindig je bij het eind van de lijst.

In [2]:
# Print elementen 2, 3 en 4
print(xs[2:5])

[5, 7, 11]


In [3]:
#Print de 4e t/m de één na laatste elementen
print(xs[4:-1])

[11, 13, 17]


In [4]:
#Print de eerste drie elementen
print(xs[:3])

[2, 3, 5]


In [5]:
#Print de laatste drie elementen
print(xs[-3:])

[13, 17, 19]


- Met de notatie **[a:b:c]** bekijk je de indices van **a** tot **b** in stappen van **c**.
- Het weglaten van **a** of **b** blijft hetzelfde.

In [6]:
# Print elementen 1, 3, 5, en 7
print(xs[1:8:2])

[3, 7, 13, 19]


In [7]:
# Print de elementen met even indices
print(xs[::2])

[2, 5, 11, 17]


In [8]:
# Draai de lijst om
print(xs[::-1])

[19, 17, 13, 11, 7, 5, 3, 2]


In [9]:
# Print elementen 4, 3, 2, 1, 0
print(xs[4::-1])

[11, 7, 5, 3, 2]


### *Nested* lijsten

- Tot nu toe hebben we alleen lijsten van getallen of strings gezien, maar alles kan een element van een lijst zijn.
- Een lijst waarvan ieder element opnieuw een lijst is, noemen we een *nested* lijst, of een 2 dimensionale array.

In [10]:
matrix = [[1, 2, 3], [3, 1, 2], [2, 3, 1]]
print(matrix)

[[1, 2, 3], [3, 1, 2], [2, 3, 1]]


In [11]:
for rij in matrix:
    print(rij)

[1, 2, 3]
[3, 1, 2]
[2, 3, 1]


In [12]:
# Print rij nul van de matrix
print(matrix[0])

[1, 2, 3]


In [13]:
# Print rij 0, kolom 2
print(matrix[0][2])

3


In [14]:
producten = [[i*j for i in range(10)] for j in range(10)]
for rij in producten:
    print(rij)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 4, 8, 12, 16, 20, 24, 28, 32, 36]
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
[0, 6, 12, 18, 24, 30, 36, 42, 48, 54]
[0, 7, 14, 21, 28, 35, 42, 49, 56, 63]
[0, 8, 16, 24, 32, 40, 48, 56, 64, 72]
[0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


Een lijst is een verwijzing naar een geheugenlocatie. In de volgende code zal een verandering van **matrix2** ook **matrix** veranderen.

In [15]:
print(matrix)
matrix2 = matrix
matrix2[1][1] = 10
print(matrix)

[[1, 2, 3], [3, 1, 2], [2, 3, 1]]
[[1, 2, 3], [3, 10, 2], [2, 3, 1]]


Voor enkelvoudige lijsten konden we hier het **copy** commando voor gebruiken als we dit niet willen. Echter, voor *nested* lijsten wil je ook van iedere rij een **copy** maken.

In [16]:
print(matrix2)
matrix3 = matrix2.copy()
matrix3[1][1] = 100
print(matrix2)

[[1, 2, 3], [3, 10, 2], [2, 3, 1]]
[[1, 2, 3], [3, 100, 2], [2, 3, 1]]


We willen een zogenaamde *deep copy*.

Dit kunnen we zelf programmeren:

Of we gebruiken het **deepcopy** commando:

In [17]:
matrix4 = [rij.copy() for rij in matrix3]
print(matrix4)

[[1, 2, 3], [3, 100, 2], [2, 3, 1]]


In [18]:
from copy import deepcopy
matrix5 = deepcopy(matrix3)
print(matrix5)

[[1, 2, 3], [3, 100, 2], [2, 3, 1]]


Het NumPy package bevat heel veel functies om slim en snel met grotere 2D arrays te werken.

In [19]:
import numpy as np

m4 = np.array(producten)
print(m4)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


In [20]:
print(m4[2:7,3:6])

[[ 6  8 10]
 [ 9 12 15]
 [12 16 20]
 [15 20 25]
 [18 24 30]]


We zullen bij programmeren 2.1 niet veel werken met NumPy (al mag het wel!), maar dit kan bij vervolgvakken wel langskomen. Zie [https://numpy.org/doc/](https://numpy.org/doc/) voor meer info.

### Tuples

Tuples zijn 2-tallen, 3-tallen, ..., of $n$-tallen van variabelen. Ze worden vaak gebruikt als een soort tijdelijke korte lijstjes:

In [21]:
t = ('Robert', 42)
print(type(t))
print(t)

<class 'tuple'>
('Robert', 42)


We kunnen de waarden in een *tuple* uitpakken in meerdere variabelen:

In [22]:
naam, leeftijd = t
print(naam, leeftijd)

Robert 42


Zo kunnen we bijvoorbeeld de waarden van twee variabelen omwisselen:

In [23]:
x = 10
y = 20
print(f"x={x}, y={y}")
x, y = y, x
print(f"x={x}, y={y}")

x=10, y=20
x=20, y=10


We kunnen een functie meerdere uitvoeren geven:

In [24]:
def abc_formule(a, b, c):
    disc = b*b - 4*a*c
    x1 = (-b + disc**0.5)/(2*a)
    x2 = (-b - disc**0.5)/(2*a)
    return x1, x2

print(abc_formule(1, 3, -4))

(1.0, -4.0)


We kunnen een *tuple* ook *uitpakken* naar de argumenten van een functie door een **\*** voor de tuple te plaatsen.

In [25]:
abc = (1, 3, -4)

print(abc_formule(abc[0], abc[1], abc[2]))

# Dit kan korter met
print(abc_formule(*abc))


(1.0, -4.0)
(1.0, -4.0)


Het **zip** commando combineert meerdere lijsten tot een lijst van tuples:

In [26]:
xs = [2, 3, 5]
ys = [7, 11, 13]
zs = [17, 19, 23]
print(list(zip(xs, ys, zs)))

[(2, 7, 17), (3, 11, 19), (5, 13, 23)]


Dit hadden we al eerder gezien binnen een **for** loop:

In [27]:
for x, y, z in zip(xs, ys, zs):
    print(x*y*z)

238
627
1495


Tuples kunnen met elkaar vergeleken worden met **<**, **<=**, **>**, **>=**, **==** en **!=**.

- Vergelijkingen werken van links naar rechts.
- **(a, b) < (c, d)** is **True** als
  - **a < c**, of als
  - **a = c** en **b < d**.
- Ook de **max** en **min** functies kunnen zo dus gebruikt worden.

Zo kan je bijvoorbeeld het minimum, en de index waar dit minimum voorkomt vinden:

In [28]:
xs = [3, 8, 99, 2, 5, 3, 8, 12, 4]
xmin, ind = min((x, i) for i, x in enumerate(xs))
print(f"xmin = {xmin} op index {ind}")

xmin = 2 op index 3


Tuples lijken heel erg op lijsten, maar er zijn een paar belangrijke verschillen:

- De elementen van lijsten kunnen veranderen, de code **mijn_lijst[3] = 25** is toegestaan
- De lengte van een lijst kan veranderen, we kunnen elementen toevoegen (met **append** of **extend**) of verwijderen (met **clear** of **pop**).
- De elementen van tuple kunnen niet veranderen, de code **mijn_tuple[3] = 25** geeft een foutmelding.
- De lengte van een tuple kan niet veranderen.

Om deze reden noemen we tuples *immutable* en lijsten *mutable*.


### Dictionaries

Soms is het werken met een lijst met indices onhandig, in veel situaties is zo'n index niet *logisch*. Bijvoorbeeld als we lijsten van studenten en hun cijfers hebben:

In [29]:
studenten = ['Jan', 'Sara', 'Piet', 'Anna']
cijfers = [7, 9, 6, 6]

Om het cijfer van iemand te vinden zouden we eerst de index moeten opzoeken, en dan het cijfer bij deze index.

In [30]:
naam = input('Van wie wil je het cijfer weten? ')
i = studenten.index(naam)
print(f"Het cijfer van {naam} is {cijfers[i]}")

Van wie wil je het cijfer weten? Jan
Het cijfer van Jan is 7


Dit is omslachtig, en gevoelig voor fouten. De oplossing hiervoor is het gebruik van een *dictionary*.

Een *dictionary* is een lijst van *keys* met bijbehorende *values*. Het werkt als een woordenboek -- je zoekt een woord (de *key*) op en krijgt zijn definitie (de *value*). De *key* is dus eigenlijk de index van een lijst.

In [31]:
cijfers = {'Jan':7, 'Sara':9, 'Piet':6, 'Anna':6}
print(type(cijfers))
print(cijfers)

<class 'dict'>
{'Jan': 7, 'Sara': 9, 'Piet': 6, 'Anna': 6}


In [32]:
naam = input('Van wie wil je het cijfer weten? ')
print(f"Het cijfer van {naam} is {cijfers[naam]}")

Van wie wil je het cijfer weten? Sara
Het cijfer van Sara is 9


Er zijn een aantal regels voor wat je als *key* kan gebruiken. De *key* moet *immutable* zijn.

|Wat mag wel? | Wat mag niet?|
|:------------|:-------------|
| Getallen | Lijsten |
| Strings | Dictionaries |
| Tuples van getallen of strings | Tuples van lijsten of dictionaries|

Met een dictionary kan je de volgende operaties uitvoeren:

| Code | Betekenis |
|------|-----------|
| **dic[k]** | De *value* bij *key* **k** |
| **dic[k] = v** | Ken de *value* **v** toe aan *key* **k**, voeg deze *key* toe indien nodig|
| **k in dic** | **True** als **dic k** als *key* heeft |
| **for k in dic:** | Loop over de *keys* |
| **for k, v in dic.items():** | Loop over de *key*, *value* paren |
| **dic.keys()** | Een lijst van de *keys* |
| **dic.values()** | Een lijst van de *values* |
| **dic.update(dic2)** | Voeg de *key*, *value* paren uit **dic2** toe aan **dic** |

Zie ook de helpfile voor **dict** voor meer opties.


In [33]:
help(dict)

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |  

In [34]:
print(cijfers['Anna'])

6


In [35]:
print('Anna' in cijfers)

True


In [36]:
for k in cijfers:
    print(k)

Jan
Sara
Piet
Anna


In [37]:
for k, v in cijfers.items():
    print(k, v)

Jan 7
Sara 9
Piet 6
Anna 6


In [38]:
print(cijfers)
cijfers.update({'Anna':8, 'Michiel':5})
print(cijfers)

{'Jan': 7, 'Sara': 9, 'Piet': 6, 'Anna': 6}
{'Jan': 7, 'Sara': 9, 'Piet': 6, 'Anna': 8, 'Michiel': 5}


Een combinatie van dictionaries en lijsten word soms gebruikt om data op te slaan:

Het bestand getallenxyz.txt heeft de volgende structuur:

        X  ,     Y  ,     Z   
     +2.038,  +1.233,  +0.435
     +0.052,  -1.155,  +1.239
     -0.266,  -0.006,  +0.144

De volgende code leest dit in:

In [39]:
file = open('getallenxyz.txt')

# Lees eerste regels met kolomnamen
labels = {label.strip() for label in file.readline().split(',')}

# Initialiseer data als een dictionary van lege
# lijsten, en vul deze aan.
data = {label:[] for label in labels}
for regel in file:
    waardes = [float(v) for v in regel.split(',')]
    for label, waarde in zip(labels, waardes):
        data[label].append(waarde)
        
print(f"""
Totaal X = {sum(data['X']):.3f}, 
Totaal Y = {sum(data['Y']):.3f}, 
Totaal Z = {sum(data['Z']):.3f}.""")


Totaal X = 54.702, 
Totaal Y = 0.013, 
Totaal Z = 71.221.


### Verzamelingen

In de wiskunde kennen we het begrip een verzameling. Dit is een lijst van waardes, zonder volgorde, en zonder dubbele waardes.

Ook Python kent verzamelingen:

In [40]:
verzameling = {2, 3, 5, 7, 11}
print(type(verzameling))
print(verzameling)

<class 'set'>
{2, 3, 5, 7, 11}


Met het **set** commando kunnen we een lijst omzetten naar een verzameling, dit heeft het effect dat alle dubbele waardes verwijderd worden.

In [41]:
verzameling = set([2, 3, 3, 3, 5, 5, 7, 11, 11])
print(verzameling)

{2, 3, 5, 7, 11}


Met verzamelingen kunnen we de volgende operaties uitvoeren:

| Code | Wiskundige notatie | Betekenis |
|------|--------------------|-----------|
| **A \| B** | $A \cup B$ | Vereniging (*union*) van $A$ en $B$ |
| **A & B** | $A \cap B$ | Doorsnijding (*intersection*) van $A$ en $B$ |
| **A - B** | $A \setminus B$ | Verwijder de elementen van $B$ uit $A$ |
| **x in A** | $x \in A$ | **True** als $x$ een element van $A$ is |
| **A < B** | $A \subset B$ | **True** als $A$ een stricte deelverzameling van $B$ is |
| **A <= B** | $A \subseteq B$ | **True** als $A$ een deelverzameling van $B$ is |
| **for x in A:** || Loop over de elementen van $A$ |

In [42]:
A = {2, 3, 5, 7, 11, 13}
B = {7, 11, 13, 17, 19}

In [43]:
print(A | B)

{2, 3, 5, 7, 11, 13, 17, 19}


In [44]:
print(A & B)

{11, 13, 7}


In [45]:
print(A - B)

{2, 3, 5}


In [46]:
print(A < B)

False


In [47]:
print({2,3} < A)

True


In [48]:
for x in A:
    print(x**2)

4
9
25
49
121
169


In [49]:
print(sum(x**2 for x in B))

989


## Programmeerstijl

- Voor *dictionaries*, *tuples* en *sets* gelden dezelfde naamgevingsregels als voor lijsten.
- De naam van een *dictionary* verwijsd naar de *value*, niet de *key*.


De keuze voor datastructuur (list, dict of set) is heel belangrijk, de juiste keuze kan leiden tot veel kortere en leesbaardere code. Denk hier goed over na! Het kan handig zijn jezelf de volgende vragen te stellen:
- Is volgorde van elementen belangrijk? (lijst)
- Moet je kunnen zoeken? (dictionary)
- Moeten elementen uniek zijn? (set)